export enum Roles {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MODERATOR = "MODERATOR",
  DONATOR = "DONATOR",
  USER = "USER",
  READER = "READER",
  GUEST = "GUEST",
  MEMBER = "MEMBER",
  TRANSLATOR = "TRANSLATOR",
  TYPESETTER = "TYPESETTER",
  CLEANER = "CLEANER",
  EDITOR = "EDITOR",
  PROOFREADER = "PROOFREADER",
}

export enum RolesCategories {
  ADMINISTRATION = "ADMINISTRATION",
  STANDARD = "STANDARD",
  GROUPS = "GROUPS",
}
